version: '3.8'

services:
  laravel:
    image: webdevops/php-apache:8.2
    container_name: laravel-test
    restart: unless-stopped
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
    volumes:
      - ./:/app
    networks:
      - npm_proxy

# Add this at the bottom
networks:
  npm_proxy:
    external: true
    name: npm_default  
